export default [
  {
    src: 'http://112.13.105.87/mp3.9ku.com/m4a/542227.m4a',
    poster: 'http://file.bywei.cn/music/chuhe/cover.jpg',
    name: '唐诗联唱',
    author: ''
  }, {
    src: 'http://audio.xmcdn.com/group11/M08/7F/F6/wKgDa1Ys7lCj6RckAA9Jmw1_hyc928.m4a',
    poster: 'http://file.bywei.cn/music/cgx.jpg',
    name: '长相思',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group10/M0B/8C/8A/wKgDaVYs7kXifOC2ABXq19FJcZg219.m4a',
    poster: 'http://file.bywei.cn/music/cgx.jpg',
    name: '长歌行',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group10/M0B/8C/78/wKgDZ1Ys7jehSBmIACMdHH-boLc142.m4a',
    poster: 'http://file.bywei.cn/music/yzy.jpg',
    name: '游子呤',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group9/M06/8C/53/wKgDYlYs7hnAdBtbAA-HNy3E3YY693.m4a',
    poster: 'http://file.bywei.cn/music/ye.jpg',
    name: '咏鹅',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group10/M06/8C/77/wKgDZ1Ys7g3wPdPBABUTUyUssa0890.m4a',
    poster: 'http://file.bywei.cn/music/yzs.jpg',
    name: '一字诗',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group14/M08/8D/10/wKgDY1Ys7fygbSdLAA8k7759br0632.m4a',
    poster: 'http://file.bywei.cn/music/xhyj.jpg',
    name: '寻胡隐君',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group14/M08/8C/CC/wKgDZFYs7fKwcbIGAA6yoPrr_h0841.m4a',
    poster: 'http://file.bywei.cn/music/xc.jpg',
    name: '晓窗',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group14/M08/8C/CC/wKgDZFYs7eqgYr8RABeuo2VYqRU428.m4a',
    poster: 'http://file.bywei.cn/music/xiangs.jpg',
    name: '相思',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group12/M00/8C/6A/wKgDW1Ys7diDhuWrABimpWUUPVs071.m4a',
    poster: 'http://file.bywei.cn/music/qinm.jpg',
    name: '清明',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group12/M00/8C/36/wKgDXFYs7cOB0EgBABYDx_ocWqc523.m4a',
    poster: 'http://file.bywei.cn/music/qbs.jpg',
    name: '七步诗',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group7/M0A/8D/2A/wKgDWlYs7bWAsl14ABwT2Cr0WIc387.m4a',
    poster: 'http://file.bywei.cn/music/mrg.jpg',
    name: '明日歌',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group7/M0A/8D/26/wKgDX1Ys7ZvgoG96ABV55OSpz7o379.m4a',
    poster: 'http://file.bywei.cn/music/ll.jpg',
    name: '悯农',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group10/M07/8C/77/wKgDZ1Ys7YziFyRsAB9sYYklbUY516.m4a',
    poster: 'http://file.bywei.cn/music/jys.jpg',
    name: '静夜思',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group7/M0A/8D/29/wKgDWlYs7XLRuzBNABCchP-1PQ0733.m4a',
    poster: 'http://file.bywei.cn/music/jn.jpg',
    name: '江南',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group15/M08/8C/B2/wKgDaFYs7WaixdjzAB3mMTxF7tw256.m4a',
    poster: 'http://file.bywei.cn/music/ysc.jpg',
    name: '赋得古草原送别',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group16/M06/8C/DC/wKgDbFYs7TqQFahIABLUMue-ySg608.m4a',
    poster: 'http://file.bywei.cn/music/cgx.jpg',
    name: '登鹳雀楼',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group16/M06/8C/DC/wKgDbFYs7S3y7yj5ABF-ar8CKQo556.m4a',
    poster: 'http://file.bywei.cn/music/cj.jpg',
    name: '村居',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group14/M07/8D/0E/wKgDY1Ys7RWgf6d9AB1gtew-lBM672.m4a',
    poster: 'http://file.bywei.cn/music/cs.jpg',
    name: '出塞',
    author: '',
  }, {
    src: 'http://audio.xmcdn.com/group41/M01/33/32/wKgJ8lquQHvy7yplABUdmLbbDRg277.m4a',
    poster: 'http://imagev2.xmcdn.com/group40/M04/F7/B7/wKgJT1quQPnAgmB4AABnIGRnMRQ099.jpg',
    name: '一字诗 （清）陈沆',
    author: '',
  }
]